### ISSUE TITLE
snowflakeintegration-linux fails with ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by paulsewardasc** [newrelic/newrelic-snowflake-integration#1]
[NOTE]: # ( ^^ After exporting the environmental variables and running ./snowflakeintegration-linux I get an error (see below) ^^ )

## Description

`internal/fs/utils.js:537
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:450:10)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:487:32)
    at Object.readFileSync (fs.js:360:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:683:36)
    at Object.<anonymous> (/snapshot/newrelic-snowflake-integration/snowflake.js:30:21)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

I have these set:

`
export NEWRELIC_SNOWFLAKE_HOME=/opt/snowflake/
export SNOWSQL_ACCOUNT=ps123456.eu-west-1.snowflakecomputing.com
export SNOWSQL_USER=NEWRELIC
export SNOWSQL_PWD=XXXX@#YYYY
export SNOWSQL_ROLE=ACCOUNTADMIN
`

**Comment by paulsewardasc** [comment]
I am now seeing 

/bin/sh: 62149NEWRELIC_SNOWFLAKE_HOME/snowflakeintegration-linux: No such file or directory

when running `FROM SnowflakeAccount SELECT error_msg`

**Comment by danifitz** [comment]
Hi @paulsewardasc I think this was related to not having the binary set as executable and not passing the code a query, as such it's not a bug. I have updated the README to ensure there is instruction to make it executable.
