### ISSUE TITLE
After Snowflake integration, data not available under SnoflakeAccount/Warehouse events 

### ISSUE THREAD

**Issue by hemamovishub** [newrelic/newrelic-snowflake-integration#34]
<img width="473" alt="Screen Shot 2022-08-08 at 11 31 52 AM" src="https://user-images.githubusercontent.com/43555156/183467593-e978c785-7b41-47df-8a7e-94b66cbd8ff6.png">

**Comment by adlangx** [comment]
This issue may have a solution

https://github.com/newrelic/newrelic-snowflake-integration/issues/22#issuecomment-1003318715

**Comment by hemamovishub** [comment]
I see errors as below under dimensions 

/bin/sh: 1: 477628NEWRELIC_SNOWFLAKE_HOME/snowflakeintegration-macos: not found

**Comment by adlangx** [comment]
Try looking in the flexconfig that you put in the /etc/newrelic-infra/integrations.d directory (I think in your case it would be the flex-snowflake-mac.yml config). Replace $$NEWRELIC_SNOWFLAKE_HOME with the actual path for example /home/<username>/newrelic-snowflake-integration/

**Comment by hemamovishub** [comment]
Yes I tried but not able to see the metrics yet

**Comment by adlangx** [comment]
I have the same issue. It appears that changing to the path instead of the variable had worked for someone in an earlier issue. I am not sure why it is not working now.

**Comment by hemamovishub** [comment]
I replaced the path, still not working.

**Comment by adlangx** [comment]
Can you see if the Snowflake user that you have in the config.yml logs in when you restart the service?

**Comment by adlangx** [comment]
We had a query that was hanging. Perhaps the same issue.

See #35

**Comment by hemamovishub** [comment]
After I replaced the path, I getting this
"Error parsing config.yaml file, make sure its a valid yaml file YAMLReferenceError: Aliased anchor not found: #######"

**Comment by thatguythat1031** [comment]
> After I replaced the path, I am getting this error message:
> 
> /snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/errors.js:218 throw createError(errorTypes.MissingParameterError, ^ Error [MissingParameterError]: A user name must be specified. at createError (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/errors.js:535:15) at Object.checkArgumentExists (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/errors.js:218:11) at new ConnectionConfig (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/connection/connection_config.js:142:12) at createConnection (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/core.js:73:7) at Object.createConnection (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/core.js:97:16) at Object. (/snapshot/newrelic-snowflake-integration/snowflake.js:87:26) at Module._compile (pkg/prelude/bootstrap.js:1320:22) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10) at Module.load (internal/modules/cjs/loader.js:984:32) at Function.Module._load (internal/modules/cjs/loader.js:877:14) { code: 404003, sqlState: undefined, data: undefined, response: undefined, responseBody: undefined, cause: undefined, isFatal: undefined }

I had this same error and found that the problem was specifying credentials.username instead of credentials.user in the config.yaml file.
