### ISSUE TITLE
SnowFlake NR integration throwing error.js:221 and error in reading config.yaml

### ISSUE THREAD

**Issue by RohitSachdeva-MPG** [newrelic/newrelic-snowflake-integration#52]
Config file example which is being used on server.
credentials:
   useKeyPairAuth: true
   privateKeyPath: /home/user/privatekey.txt
   account: **
   username: **
   role: **
  warehouse: **

When I am trying to run the ./snowflakeintegration-linux binaries, it is throwing error 
Error reading config.yaml file TypeError [Err_INVALID_ARG_TYPE]: The path argument must be of type string or an instance of buffer or URL. Received Undefined.

In NRDB I was seeing the error exit status 127 & /bin/sh/(somerandomnumber)NEWRELIC_SNOWFLAKE_HOME/snowflakeintegration-linux no such file or directory in NRDB.

After that I changed the flexconfig.yaml and replace NEWRELIC_SNOWFLAKE_HOME variable with the exact path and now I can see exit code 1 error along with /snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/error.js:221 throw createError(errorTypes.MissingParameterError,^ Error[MissingParameterError]: A username must be specified. at create error( /snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/error.js:538:15) at Object.CheckArgumentExists  /snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/error.js:221:11) at new connectionConfig  /snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/error.js:147:12) at create connection  /snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/core.js:73:7) at.....

**Comment by RohitSachdeva-MPG** [comment]
After making the changes in config.yaml file using user instead of username  it is throwing below error.
It is clearly showing the error is with privatekeypair, could some 1 tell how to parse the same.

credentials:
useKeyPairAuth: true
privateKeyPath: /home/user/privatekey.txt
account: **
user: **
role: **
warehouse: **

/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/connection/connection.js:219 throw authErr; ^ TypeError: Passphrase required for encrypted key at Object.createPrivateKey (node:internal/crypto/keys:618:12) at loadPrivateKey (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/authentication/auth_keypair.js:94:33) at auth_keypair.authenticate (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/authentication/auth_keypair.js:169:20) at Connection.connect (/snapshot/newrelic-snowflake-integration/node_modules/snowflake-sdk/lib/connection/connection.js:201:12) at Object.<anonymous> (/snapshot/newrelic-snowflake-integration/snowflake.js:97:12) at Module._compile (pkg/prelude/bootstrap.js:1930:22) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Function.runMain (pkg/prelude/bootstrap.js:1983:12) { code: 'ERR_MISSING_PASSPHRASE' }
